apiVersion: v1
kind: ConfigMap
metadata:
  name: sre-project-config
  namespace: {{ .Values.namespace }}

  labels:
    {{- include "sre-project.labels" . | nindent 4 }}

data:
  APP_ENV: {{ .Values.config.app_env | quote }}
  LOG_LEVEL: {{ .Values.config.log_level | quote }}