apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgres.configmapName }}
  namespace: {{ .Values.namespace }}

  labels:
    {{- include "sre-project.labels" . | nindent 4 }} 

data:
  postgresql.conf: |
    wal_level = replica
    max_wal_senders = 2
    max_replication_slots = 1
    hot_standby = on
    listen_addresses = '*'
    wal_keep_size = 256MB
    hba_file = '/etc/postgresql/pg_hba.conf'

  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    host    all             all             0.0.0.0/0               md5
    host    all             all             ::/0                    md5
    local   all             all                                     trust
    host    replication     replicator      0.0.0.0/0               md5