apiVersion: v1
kind: Service
metadata:
  name: postgres-replica
  namespace: {{ .Values.namespace }}

  labels:
    {{- include "sre-project.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: postgres-replica
  ports:
    - protocol: TCP 
      port: 5432
      targetPort: 5432