apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: {{ .Values.namespace }}

  labels:
    {{- include "sre-project.labels" . | nindent 4 }}

spec:
  schedule: {{ .Values.backup.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.backup.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.backup.failedJobsHistoryLimit }}

  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure

          containers:
            - name: postgres-backup
              image: {{ .Values.postgres.image }}

              env:
                - name: PGHOST
                  value: {{ .Values.backup.host }}

                - name: PGDATABASE
                  value: {{ .Values.postgres.database }}

                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.postgres.existingSecret }}
                      key: username

                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.postgres.existingSecret }}
                      key: password

              command:
                - /bin/sh
                - -c
                - |
                  mkdir -p /backup

                  pg_dump \
                    -h $PGHOST \
                    -U $PGUSER \
                    -d $PGDATABASE \
                    -F p \
                    -f /backup/tasksdb-$(date +%F-%H-%M-%S).sql

                  echo "Backup completed."

              volumeMounts:
                - name: backup-storage
                  mountPath: /backup

          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: {{ .Values.backup.pvc }}