apiVersion: v1
kind: Service
metadata:
  name: sre-project-service
  namespace: {{ .Values.namespace }}

  labels:
    {{- include "sre-project.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  selector:
    app: sre-project-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port}}
      targetPort: {{ .Values.service.targetPort}}