apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-replica
  namespace: sre-project

spec:
  serviceName: postgres-replica
  replicas: 1

  selector:
    matchLabels:
      app: postgres-replica

  template:
    metadata:
      labels:
        app: postgres-replica

    spec:
      initContainers:
        - name: clone-primary
          image: postgres:13-alpine

          env:
            - name: PGDATA
              value: /var/lib/postgresql/data
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-replication-secret
                  key: password

          command:
            - /bin/sh
            - -c
            - |
              if [ ! -s /var/lib/postgresql/data/PG_VERSION ]; then

                echo "Starting pg_basebackup..."

                pg_basebackup \
                  -h postgres \
                  -U replicator \
                  -D /var/lib/postgresql/data \
                  -Fp \
                  -X stream \
                  -P \
                  -R \
                  -S replica_slot

                echo "Primary cloned successfully."

              else

                echo "Replica already initialized."

              fi

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

      containers:
        - name: postgres
          image: postgres:13-alpine

          env:
            - name: POSTGRES_DB
              value: tasksdb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sre-project-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sre-project-db-credentials
                  key: password

          ports:
            - containerPort: 5432
              name: postgres

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
    - metadata:
        name: postgres-storage

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-replica
  namespace: sre-project
spec:
  clusterIP: None
  selector:
    app: postgres-replica
  ports:
     - port: 5432
       targetPort: 5432