apiVersion: v1
kind: Service
metadata:
  name: sre-project-service
  namespace: sre-project
spec:
  type: ClusterIP
  selector:
    app: sre-project-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
